### PR TITLE
Use parent on layout inflation

### PR DESCRIPTION
**Pull request by ceasingone**

### CODE REVIEW

**Comment by chrislim** [comment]
What happens if we don't use parent?

**Comment by ceasingone** [comment]
A cautionary tale:
https://possiblemobile.com/2013/05/layout-inflation-as-intended/

**Comment by ceasingone** [comment]
Basically, it doesn't inherit attributes as it ought...think cascading style sheets without proper cascading.

**Comment by chrislim** [comment]
ah, thanks!

**Pull request merged**
