### PR TITLE
Issue86 enhancement add people favorite tab

### PR DESCRIPTION
**Pull request by evandyang**
Added a Favorite tab to the People fragment.

### CODE REVIEW

**Comment by chrislim** [comment]
Please resolve the merge conflicts (e.g. https://github.com/ceaseless-prayer/CeaselessAndroid/pull/101/files#diff-ddb55b5f72909f0ea45dfeac0cdbc8b2R44)

**Comment by evandyang** [comment]
Addressed merge conflicts and also CI failure.

**Comment by chrislim** [comment]
Looks good, I'll merge this, but quick question: do you think we should have the favorite icon in the favorite list? I know you left it out and just wanted to know your thoughts on it.

Also, we need to update the localization files since you've added the new "Favorite" string.

**Comment by evandyang** [comment]
I left the Favorite icon out because I thought it was redundant to show the favorite icon in the Favorite tab. That being said, I could add the favorite icons if desired. I imagine seeing all those filled hearts would be nice :)

**Pull request merged**
